#ifndef APP_LAYER_STACK_H
#define APP_LAYER_STACK_H

typedef enum {
    APP_LAYER_STACK_NONE = 0,
    APP_LAYER_STACK_ADD_TOP,
    APP_LAYER_STACK_INSERT_ABOVE,
    APP_LAYER_STACK_INSERT_BELOW,
    APP_LAYER_STACK_TOGGLE_LOCK,
    APP_LAYER_STACK_TOGGLE_LOCK_OTHERS,
    APP_LAYER_STACK_TOGGLE_VISIBILITY_OTHERS,
    APP_LAYER_STACK_UNLOCK_ALL,
    APP_LAYER_STACK_FLATTEN,
    APP_LAYER_STACK_STAMP_VISIBLE_INTO,
    APP_LAYER_STACK_STAMP_VISIBLE_NEW,
    APP_LAYER_STACK_DUPLICATE_BELOW,
    APP_LAYER_STACK_DUPLICATE,
    APP_LAYER_STACK_MOVE_RELATIVE,
    APP_LAYER_STACK_MOVE_TO_EDGE,
    APP_LAYER_STACK_ADJUST_OPACITY,
    APP_LAYER_STACK_TOGGLE_VISIBILITY,
    APP_LAYER_STACK_HIDE_AND_ADVANCE,
    APP_LAYER_STACK_TOGGLE_SOLO,
    APP_LAYER_STACK_DELETE,
    APP_LAYER_STACK_MERGE_DOWN,
    APP_LAYER_STACK_MERGE_UP,
    APP_LAYER_STACK_RESET_OPACITY,
    APP_LAYER_STACK_SHOW_ALL,
    APP_LAYER_STACK_SHOW_ACTIVE
} AppLayerStackAction;

typedef struct {
    int handled;
    AppLayerStackAction action;
    int argument;
} AppLayerStackCommand;

AppLayerStackCommand app_layer_stack_command_for_key(int key, int ctrl, int shift);

#endif
