#ifndef CANVAS_SHORTCUTS_H
#define CANVAS_SHORTCUTS_H

typedef enum {
    CANVAS_SHORTCUT_NONE = 0,
    CANVAS_SHORTCUT_CLEAR,
    CANVAS_SHORTCUT_FLIP_HORIZONTAL,
    CANVAS_SHORTCUT_FLIP_VERTICAL,
    CANVAS_SHORTCUT_ROTATE_180,
    CANVAS_SHORTCUT_INVERT_RGB,
    CANVAS_SHORTCUT_FILL,
    CANVAS_SHORTCUT_EYEDROPPER
} CanvasShortcutAction;

CanvasShortcutAction canvas_shortcut_action(int key);

#endif
