#ifndef LAYER_NAME_SHORTCUTS_H
#define LAYER_NAME_SHORTCUTS_H

typedef enum {
    LAYER_NAME_RESET_SHORTCUT_NONE = 0,
    LAYER_NAME_RESET_SHORTCUT_ACTIVE,
    LAYER_NAME_RESET_SHORTCUT_ALL,
    LAYER_NAME_RESET_SHORTCUT_UNLOCKED,
    LAYER_NAME_RESET_SHORTCUT_VISIBLE,
    LAYER_NAME_RESET_SHORTCUT_NON_BACKGROUND_UNLOCKED,
    LAYER_NAME_RESET_SHORTCUT_LOCKED,
    LAYER_NAME_RESET_SHORTCUT_NON_BACKGROUND_VISIBLE,
    LAYER_NAME_RESET_SHORTCUT_NON_BACKGROUND_LOCKED
} LayerNameResetShortcut;

LayerNameResetShortcut layer_name_reset_shortcut_from_modifiers(int ctrl, int alt, int shift);

#endif
