#ifndef PAINT_SHORTCUTS_H
#define PAINT_SHORTCUTS_H

typedef enum {
    PAINT_SHORTCUT_NONE = 0,
    PAINT_SHORTCUT_TOOL_BRUSH,
    PAINT_SHORTCUT_TOOL_ERASER,
    PAINT_SHORTCUT_TOOL_LINE,
    PAINT_SHORTCUT_TOOL_RECT,
    PAINT_SHORTCUT_TOOL_FILLED_RECT,
    PAINT_SHORTCUT_TOOL_ELLIPSE,
    PAINT_SHORTCUT_TOOL_FILLED_ELLIPSE,
    PAINT_SHORTCUT_COLOR_BRUSH,
    PAINT_SHORTCUT_COLOR_RED,
    PAINT_SHORTCUT_COLOR_GREEN,
    PAINT_SHORTCUT_COLOR_BLUE,
    PAINT_SHORTCUT_COLOR_YELLOW,
    PAINT_SHORTCUT_COLOR_PURPLE
} PaintShortcutAction;

PaintShortcutAction paint_shortcut_action(int key);

#endif
