#ifndef STATUS_TEXT_H
#define STATUS_TEXT_H

typedef enum {
    STATUS_LOCK_TOGGLE = 0,
    STATUS_LOCK_AND_ADVANCE,
    STATUS_LOCK_AND_RETREAT,
    STATUS_UNLOCK_ALL,
    STATUS_SHOW_UNLOCKED_ONLY,
    STATUS_SHOW_LOCKED_ONLY,
    STATUS_SHOW_HIDDEN_LOCKED_ONLY,
    STATUS_SHOW_HIDDEN_UNLOCKED_ONLY,
    STATUS_INSERT_LAYER_ABOVE,
    STATUS_INSERT_LAYER_BELOW,
    STATUS_FLATTEN_LOCKED,
    STATUS_STAMP_VISIBLE_INTO_LOCKED,
    STATUS_STAMP_VISIBLE_NEW,
    STATUS_DUPLICATE_LAYER,
    STATUS_MOVE_LAYER_BOTTOM,
    STATUS_MOVE_LAYER_TOP,
    STATUS_HIDE_FINAL_VISIBLE,
    STATUS_TOGGLE_SOLO,
    STATUS_DELETE_FINAL_OR_LOCKED,
    STATUS_MERGE_DOWN_BLOCKED,
    STATUS_MERGE_UP_BLOCKED
} StatusTextAction;

const char *status_text_action_error(StatusTextAction action);

#endif
